os:
  - osx
language: node_js
node_js:
  - "7"
  - "6"
addons:
  browserstack:
    username: "hussainashraf1"
    access_key:
      secure: "rsSKRFNukmPtPVsoYIu3tIzLhvP8erIAH4YAAh/PClhcMylsqveZf93HWeUooflchpqts4rapRXbaAIk3Su9fcqw1cbNLbw2On6YP0thxpl6bQroWQjt73C9Aa31Z4gNMRkFU7kWXKLN4mUuusJIHeMwciHO9wEzMEtPLktjIgii0enm/WeOs4qzu3oaqafgX4a1On0ZCXvX/lhL9zoNBxZajazrNBwiqY40bD82Fj7xHZG0KOkW+/BnWTnjIeS2GtUC4DoawvXHlJmJ4cPQB0rJcSWEpkg3hPzzwYYH2XhRbCo6HQY1sDXehPc7ajot/mgrXlxdDUL02rxt0/UMMvuQEcXbovzkHuKv/zfNW66wdY93bEujtlB1owHnzXM8y1jpuAKzi1UH0S6SzBuCp9Gq73NrcWTt0UNxJQoVLOhj2FwvVXsqNy5J3Apr7uOz0Cku7f6wDwLzKZogbjMWO56IEWdKWjK0+bcYHkqAvho3X5RZJircjG4dfLjs0TXO5cF8sFg3i8Y3y7m3FCxerXhSjvEKxUwgn9ipcvfbEK4Pji8ccUjljEY2L5cPyjaE297z7FSWhhbF2EXdbeSL+UD2P20Yjxmh0NfAQWprV51GI4feoOB6xyIg3VDBqXrf3QByF/KLjQPzIgpehLpJ61G+hRox0Rv3/3fP8F7rQp0="
    forcelocal: true
install: npm install
sudo: false
script:
  - npm run test
  - travis_wait 30 npm run test-generation-component
  - travis_wait 30 npm run test-install-component-dependencies
  - travis_wait 30 npm run test-install-demo-component-dependencies
  - travis_wait 30 npm run test-build-component
  - travis_wait 30 npm run test-cross-browsers
after_success:
  - npm run coveralls
  - bash <(curl -s https://codecov.io/bash)
