language: node_js
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'
install: npm install
sudo: false
after_success:
  - npm run-script test
  - npm run coveralls
after_success:
  - bash <(curl -s https://codecov.io/bash)
